apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: kyverno
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: git
  override:
    enableShellInRendering: true
  git:
    repo: git@github.com:procter-gamble/k8s-kyverno.git
    dir: charts/kyverno-system
    branch: krasus-configsync
    auth: ssh
    secretRef:
      name: kyverno-secret
    # Use the optional field spec.helm.values to override default values.
    # You can use the same format as the default values file to override
    # default values.
