# helmCharts:
# - name: cert-manager
#   repo: https://charts.jetstack.io
#   version: v1.5.3
#   releaseName: my-cert-manager
#   namespace: kyverno-system
helmCharts:
- name: prometheus
  repo: https://github.com/prometheus-community/helm-charts/tree/main/charts
  releaseName: test
  namespace: kyverno-system
  includeCRDs: true
